In [ ]:
#from sk_tool import SKToolInitializer as skti

In [2]:
from pisces_params import PiSetup

In [3]:
from qcluster import RunNode

In [4]:
import pickle

In [5]:
rn=RunNode(qdict=1,local_run=1)

In [6]:
p=PiSetup(test=True)

In [7]:
runlist,hash_id_list=p.setupRunners()

In [8]:
len(runlist)

21

In [9]:
#runlist[0].rundict

In [10]:
#runner1=runlist[4]

In [11]:
predictresult_list=[]
for runner in runlist[:1]:
    runner.build()
    predictresult_list.append(runner.run())

In [12]:
predictresult=predictresult_list[0]

In [13]:
type(predictresult['coef_scor_df'])

pandas.core.frame.DataFrame

In [14]:
predictresult['coef_scor_df']#.sum(axis=1,level='rep_idx')

,var,scorer:f1_micro,scorer:roc_auc_score_macro,scorer:roc_auc_score_micro,scorer:precision_micro,scorer:recall_micro,AgKffactCat,AgKffactWs,Al2O3Cat,Al2O3Ws,BFICat,...,WCONN_v2_1,WHABT_v2_1,WHYD_v2_1,WSED_v2_1,WTEMP_v2_1,WetIndexCat,WetIndexWs,WtDepCat,WtDepWs,prG_BMMI
,rep_idx,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
,split_idx,0,0,0,0,0,0,0,0,0,0,...,4,4,4,4,4,4,4,4,4,4
species,estimator,,,,,,,,,,,,,,,,,,,,,
etheostoma mariae,logistic-reg,0.9,0.9375,0.9375,0.9,0.9,0.0,0.0,-0.005351,0.0,0.0,...,0.0,0.0,0.0,0.048291,0.0,0.0,0.0,0.0,0.0,0.038426

In [15]:
predictresult['yhat'].sum(axis=1,level='rep_idx')

rep_idx                                                0    1
species           estimator    HUC12        COMID
etheostoma mariae logistic-reg 030402040303 9109774  0.0  1.0
                               030402010303 9167552  0.0  0.0
                               030402010301 9165154  0.0  0.0
                               030402010401 9169724  0.0  0.0
                               030402011202 9179526  0.0  0.0
                               030402040302 9110340  1.0  1.0
                               030402040101 9109734  1.0  1.0
                               030402010710 9173814  0.0  0.0
                               030402010102 9164108  1.0  0.0
                               030402010902 9174894  0.0  0.0
                               030402030901 9128028  0.0  0.0
                               030402010305 9165758  0.0  0.0
                               030402030206 9129024  1.0  1.0
                               030402030202 9125600  1.0  0.0
                               030402040103 9108826  1.0  1.0
                               030402030403 9129936  0.0  0.0
                               030402010201 9165476  0.0  0.0
                               030402040301 9109780  1.0  1.0
                               030402030205 9125742  1.0  1.0
                               030402040809 9116090  0.0  0.0
                               030402031205 9132658  0.0  0.0
                               030402031401 9134066  0.0  0.0
                               030402010203 9165524  0.0  0.0
                               030402030103 9125528  1.0  1.0
                               030402011202 9179728  0.0  0.0
                               030402010806 9175110  0.0  0.0
                               030402010202 9169462  0.0  0.0
                               030402010604 9171030  0.0  0.0
                               030402031103 9131446  0.0  0.0
                               030402030206 9125840  1.0  1.0
                               030402010102 9165160  0.0  1.0
                               030402010101 9164090  0.0  0.0
                               030402040505 9114230  0.0  0.0
                               030402010410 9167744  0.0  0.0
                               030402040303 9108736  0.0  0.0
                               030402030102 9125326  1.0  1.0
                               030402010506 9166156  0.0  0.0
                               030402030201 9125896  1.0  1.0
                                            9125542  1.0  1.0
                               030402030101 9125376  1.0  1.0
                               030402040808 9113812  0.0  0.0
                               030402031205 9134612  0.0  0.0
                               030402030302 9129546  0.0  0.0
                               030402040602 9111040  0.0  0.0
                               030402030103 9125908  1.0  1.0
                               030402010101 9164008  0.0  0.0
                               030402010201 9169408  0.0  0.0

In [16]:
predictresult['y']

                                        y
species           HUC12        COMID
etheostoma mariae 030402040303 9109774  0
                  030402010303 9167552  0
                  030402010301 9165154  0
                  030402010401 9169724  0
                  030402011202 9179526  0
                  030402040302 9110340  1
                  030402040101 9109734  1
                  030402010710 9173814  0
                  030402010102 9164108  0
                  030402010902 9174894  0
                  030402030901 9128028  0
                  030402010305 9165758  0
                  030402030206 9129024  1
                  030402030202 9125600  0
                  030402040103 9108826  1
                  030402030403 9129936  0
                  030402010201 9165476  0
                  030402040301 9109780  1
                  030402030205 9125742  1
                  030402040809 9116090  0
                  030402031205 9132658  0
                  030402031401 9134066  0
                  030402010203 9165524  0
                  030402030103 9125528  0
                  030402011202 9179728  0
                  030402010806 9175110  0
                  030402010202 9169462  0
                  030402010604 9171030  0
                  030402031103 9131446  0
                  030402030206 9125840  1
                  030402010102 9165160  0
                  030402010101 9164090  0
                  030402040505 9114230  0
                  030402010410 9167744  0
                  030402040303 9108736  0
                  030402030102 9125326  1
                  030402010506 9166156  0
                  030402030201 9125896  1
                               9125542  1
                  030402030101 9125376  1
                  030402040808 9113812  0
                  030402031205 9134612  0
                  030402030302 9129546  0
                  030402040602 9111040  0
                  030402030103 9125908  1
                  030402010101 9164008  0
                  030402010201 9169408  0